import type { Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#111317",
        surface: "#111317",
        primary: {
          DEFAULT: "#b8c3ff",
          foreground: "#FFFFFF",
          50: "#EFF6FF",
          100: "#DBEAFE",
          200: "#BFDBFE",
          300: "#93C5FD",
          400: "#60A5FA",
          500: "#3B82F6",
          600: "#2563EB",
          700: "#1D4ED8",
          800: "#1E40AF",
          900: "#1E3A8A",
        },
        accent: {
          DEFAULT: "#8B5CF6",
          foreground: "#FFFFFF",
          50: "#F5F3FF",
          100: "#EDE9FE",
          200: "#DDD6FE",
          300: "#C4B5FD",
          400: "#A78BFA",
          500: "#8B5CF6",
          600: "#7C3AED",
          700: "#6D28D9",
          800: "#5B21B6",
          900: "#4C1D95",
        },
        glow: "#60A5FA",
        text: "#FFFFFF",
        "text-secondary": "#94A3B8",
        success: "#10B981",
        warning: "#F59E0B",
        error: "#ffb4ab",
        border: "rgba(255,255,255,0.1)",
        card: {
          DEFAULT: "rgba(11, 17, 32, 0.8)",
          foreground: "#FFFFFF",
        },
        muted: {
          DEFAULT: "#1E293B",
          foreground: "#94A3B8",
        },
        popover: {
          DEFAULT: "#0B1120",
          foreground: "#FFFFFF",
        },
        input: "rgba(255,255,255,0.08)",
        ring: "#3B82F6",
        destructive: {
          DEFAULT: "#EF4444",
          foreground: "#FFFFFF",
        },
        secondary: {
          DEFAULT: "#ddb7ff",
          foreground: "#FFFFFF",
        },
        foreground: "#FFFFFF",
        "on-surface": "#e2e2e8",
        "secondary-container": "#6f00be",
        "surface-dim": "#111317",
        "surface-variant": "#333539",
        "on-secondary": "#490080",
        "on-tertiary-fixed": "#002021",
        "on-error": "#690005",
        "tertiary-container": "#00797e",
        "inverse-primary": "#104af0",
        "surface-container-high": "#282a2e",
        "on-surface-variant": "#c4c5d9",
        "error-container": "#93000a",
        tertiary: "#00dce5",
        "on-primary": "#002387",
        "on-secondary-container": "#d6a9ff",
        "surface-bright": "#37393e",
        "surface-container": "#1e2024",
        "tertiary-fixed-dim": "#00dce5",
        "on-tertiary": "#003739",
        "outline-variant": "#434656",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-fixed-variant": "#6900b3",
        "primary-fixed-dim": "#b8c3ff",
        "primary-container": "#2d5bff",
        "on-background": "#e2e2e8",
        "inverse-surface": "#e2e2e8",
        "surface-container-lowest": "#0c0e12",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#ddb7ff",
        "on-primary-fixed": "#001355",
        "inverse-on-surface": "#2f3035",
        "on-primary-container": "#efefff",
        "surface-container-low": "#1a1c20",
        "on-tertiary-fixed-variant": "#004f53",
        "secondary-fixed": "#f0dbff",
        "primary-fixed": "#dde1ff",
        "outline": "#8e90a2",
        "on-tertiary-container": "#bafbff",
        "surface-tint": "#b8c3ff",
        "tertiary-fixed": "#63f7ff",
        "surface-container-highest": "#333539",
        "on-primary-fixed-variant": "#0035bd",
      },
      fontFamily: {
        sans: ["Inter", ...fontFamily.sans],
        heading: ["Space Grotesk", ...fontFamily.sans],
        display: ["Space Grotesk", ...fontFamily.sans],
        mono: ["JetBrains Mono", "Fira Code", ...fontFamily.mono],
      },
      fontSize: {
        "display-2xl": ["4.5rem", { lineHeight: "1.1", letterSpacing: "-0.02em" }],
        "display-xl": ["3.75rem", { lineHeight: "1.1", letterSpacing: "-0.02em" }],
        "display-lg": ["3rem", { lineHeight: "1.15", letterSpacing: "-0.02em" }],
        "display-md": ["2.25rem", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "display-sm": ["1.875rem", { lineHeight: "1.25", letterSpacing: "-0.01em" }],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "aurora-1": "linear-gradient(135deg, #3B82F6 0%, #8B5CF6 50%, #EC4899 100%)",
        "aurora-2": "linear-gradient(135deg, #06b6d4 0%, #3B82F6 50%, #8B5CF6 100%)",
        "hero-gradient": "radial-gradient(ellipse at top, rgba(59,130,246,0.15) 0%, transparent 50%)",
        "card-gradient": "linear-gradient(135deg, rgba(59,130,246,0.1) 0%, rgba(139,92,246,0.1) 100%)",
        "glass-gradient": "linear-gradient(135deg, rgba(255,255,255,0.08) 0%, rgba(255,255,255,0.03) 100%)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-in-out",
        "fade-up": "fadeUp 0.5s ease-out",
        "fade-down": "fadeDown 0.5s ease-out",
        "slide-in-right": "slideInRight 0.5s ease-out",
        "slide-in-left": "slideInLeft 0.5s ease-out",
        "scale-in": "scaleIn 0.3s ease-out",
        "glow-pulse": "glowPulse 2s ease-in-out infinite",
        "aurora": "aurora 8s ease-in-out infinite",
        "float": "float 6s ease-in-out infinite",
        "float-slow": "float 9s ease-in-out infinite",
        "particle-drift": "particleDrift 15s linear infinite",
        "shimmer": "shimmer 2s linear infinite",
        "spin-slow": "spin 8s linear infinite",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "bounce-slow": "bounce 3s infinite",
        "gradient-shift": "gradientShift 6s ease infinite",
        "typing": "typing 3.5s steps(40, end), blink-caret 0.75s step-end infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeDown: {
          "0%": { opacity: "0", transform: "translateY(-20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        glowPulse: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(59,130,246,0.3), 0 0 60px rgba(59,130,246,0.1)" },
          "50%": { boxShadow: "0 0 40px rgba(59,130,246,0.6), 0 0 100px rgba(59,130,246,0.2)" },
        },
        aurora: {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        particleDrift: {
          "0%": { transform: "translateY(100vh) translateX(0px)", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { transform: "translateY(-100px) translateX(50px)", opacity: "0" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        gradientShift: {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        typing: {
          "from": { width: "0" },
          "to": { width: "100%" },
        },
        "blink-caret": {
          "from, to": { borderColor: "transparent" },
          "50%": { borderColor: "#3B82F6" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      boxShadow: {
        "glow-sm": "0 0 15px rgba(59,130,246,0.3)",
        "glow-md": "0 0 30px rgba(59,130,246,0.4)",
        "glow-lg": "0 0 60px rgba(59,130,246,0.5)",
        "glow-purple": "0 0 30px rgba(139,92,246,0.4)",
        "glow-cyan": "0 0 30px rgba(6,182,212,0.4)",
        "glass": "0 8px 32px 0 rgba(0, 0, 0, 0.37)",
        "glass-lg": "0 25px 50px 0 rgba(0, 0, 0, 0.5)",
        "inner-glow": "inset 0 0 30px rgba(59,130,246,0.1)",
        "card": "0 4px 24px rgba(0,0,0,0.5)",
      },
      borderRadius: {
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
      },
      backdropBlur: {
        xs: "2px",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        "3xl": "40px",
      },
      spacing: {
        "18": "4.5rem",
        "22": "5.5rem",
        "26": "6.5rem",
        "30": "7.5rem",
      },
      zIndex: {
        "60": "60",
        "70": "70",
        "80": "80",
        "90": "90",
        "100": "100",
      },
      transitionDuration: {
        "400": "400ms",
        "600": "600ms",
        "800": "800ms",
        "900": "900ms",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
